///////////////////////////////////////////////////////////////////////////////
//   ____  ____ 
//  /   /\/   /
// /___/  \  /    Vendor: Xilinx
// \   \   \/     Version : 1.12
//  \   \         Application : Virtex-6 FPGA GTX Transceiver Wizard
//  /   /         Filename : gem_firefly.v
// /___/   /\     
// \   \  /  \ 
//  \___\/\___\
//
//
// Module GEM_FIREFLY (a GTX Wrapper)
// Generated by Xilinx Virtex-6 FPGA GTX Transceiver Wizard
// 
// 
// (c) Copyright 2009-2011 Xilinx, Inc. All rights reserved.
// 
// This file contains confidential and proprietary information
// of Xilinx, Inc. and is protected under U.S. and
// international copyright and other intellectual property
// laws.
// 
// DISCLAIMER
// This disclaimer is not a license and does not grant any
// rights to the materials distributed herewith. Except as
// otherwise provided in a valid license issued to you by
// Xilinx, and to the maximum extent permitted by applicable
// law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
// WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
// AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
// BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
// INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
// (2) Xilinx shall not be liable (whether in contract or tort,
// including negligence, or under any other theory of
// liability) for any loss or damage of any kind or nature
// related to, arising under or in connection with these
// materials, including for any direct, or any indirect,
// special, incidental, or consequential loss or damage
// (including loss of data, profits, goodwill, or any type of
// loss or damage suffered as a result of any action brought
// by a third party) even if such damage or loss was
// reasonably foreseeable or Xilinx had been advised of the
// possibility of the same.
// 
// CRITICAL APPLICATIONS
// Xilinx products are not designed or intended to be fail-
// safe, or for use in any application requiring fail-safe
// performance, such as life-support or safety devices or
// systems, Class III medical devices, nuclear facilities,
// applications related to the deployment of airbags, or any
// other applications that could lead to death, personal
// injury, or severe property or environmental damage
// (individually and collectively, "Critical
// Applications"). Customer assumes the sole risk and
// liability of any use of Xilinx products in Critical
// Applications, subject only to applicable laws and
// regulations governing limitations on product liability.
// 
// THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
// PART OF THIS FILE AT ALL TIMES. 


`timescale 1ns / 1ps


//***************************** Entity Declaration ****************************

(* CORE_GENERATION_INFO = "Gem_firefly,v6_gtxwizard_v1_12,{protocol_file=Start_from_scratch}" *) module Gem_firefly #
(
    // Simulation attributes
    parameter   WRAPPER_SIM_GTXRESET_SPEEDUP    = 0    // Set to 1 to speed up sim reset
)
(
    
    //_________________________________________________________________________
    //_________________________________________________________________________
    //GTX0  (X0Y0)

    //---------------------- Loopback and Powerdown Ports ----------------------
    input   [2:0]   GTX0_LOOPBACK_IN,
    //------------- Receive Ports - Comma Detection and Alignment --------------
    output          GTX0_RXCOMMADET_OUT,
    input           GTX0_RXSLIDE_IN,
    //--------------------- Receive Ports - PRBS Detection ---------------------
    input           GTX0_PRBSCNTRESET_IN,
    input   [2:0]   GTX0_RXENPRBSTST_IN,
    output          GTX0_RXPRBSERR_OUT,
    //----------------- Receive Ports - RX Data Path interface -----------------
    output  [19:0]  GTX0_RXDATA_OUT,
    input           GTX0_RXUSRCLK2_IN,
    //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
    input   [2:0]   GTX0_RXEQMIX_IN,
    input           GTX0_RXN_IN,
    input           GTX0_RXP_IN,
    //---------------------- Receive Ports - RX PLL Ports ----------------------
    input           GTX0_GTXRXRESET_IN,
    input           GTX0_MGTREFCLKRX_IN,
    input           GTX0_PLLRXRESET_IN,
    output          GTX0_RXPLLLKDET_OUT,
    output          GTX0_RXRESETDONE_OUT,
    //---------------- Transmit Ports - TX Data Path interface -----------------
    input   [19:0]  GTX0_TXDATA_IN,
    output          GTX0_TXOUTCLK_OUT,
    input           GTX0_TXUSRCLK2_IN,
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
    input   [3:0]   GTX0_TXDIFFCTRL_IN,
    output          GTX0_TXN_OUT,
    output          GTX0_TXP_OUT,
    input   [4:0]   GTX0_TXPOSTEMPHASIS_IN,
    //------------- Transmit Ports - TX Driver and OOB signalling --------------
    input   [3:0]   GTX0_TXPREEMPHASIS_IN,
    //--------------------- Transmit Ports - TX PLL Ports ----------------------
    input           GTX0_GTXTXRESET_IN,
    input           GTX0_MGTREFCLKTX_IN,
    input           GTX0_PLLTXRESET_IN,
    output          GTX0_TXPLLLKDET_OUT,
    output          GTX0_TXRESETDONE_OUT,
    //------------------- Transmit Ports - TX PRBS Generator -------------------
    input   [2:0]   GTX0_TXENPRBSTST_IN,
    input           GTX0_TXPRBSFORCEERR_IN,


    
    //_________________________________________________________________________
    //_________________________________________________________________________
    //GTX1  (X0Y1)

    //---------------------- Loopback and Powerdown Ports ----------------------
    input   [2:0]   GTX1_LOOPBACK_IN,
    //------------- Receive Ports - Comma Detection and Alignment --------------
    output          GTX1_RXCOMMADET_OUT,
    input           GTX1_RXSLIDE_IN,
    //--------------------- Receive Ports - PRBS Detection ---------------------
    input           GTX1_PRBSCNTRESET_IN,
    input   [2:0]   GTX1_RXENPRBSTST_IN,
    output          GTX1_RXPRBSERR_OUT,
    //----------------- Receive Ports - RX Data Path interface -----------------
    output  [19:0]  GTX1_RXDATA_OUT,
    input           GTX1_RXUSRCLK2_IN,
    //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
    input   [2:0]   GTX1_RXEQMIX_IN,
    input           GTX1_RXN_IN,
    input           GTX1_RXP_IN,
    //---------------------- Receive Ports - RX PLL Ports ----------------------
    input           GTX1_GTXRXRESET_IN,
    input           GTX1_MGTREFCLKRX_IN,
    input           GTX1_PLLRXRESET_IN,
    output          GTX1_RXPLLLKDET_OUT,
    output          GTX1_RXRESETDONE_OUT,
    //---------------- Transmit Ports - TX Data Path interface -----------------
    input   [19:0]  GTX1_TXDATA_IN,
    output          GTX1_TXOUTCLK_OUT,
    input           GTX1_TXUSRCLK2_IN,
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
    input   [3:0]   GTX1_TXDIFFCTRL_IN,
    output          GTX1_TXN_OUT,
    output          GTX1_TXP_OUT,
    input   [4:0]   GTX1_TXPOSTEMPHASIS_IN,
    //------------- Transmit Ports - TX Driver and OOB signalling --------------
    input   [3:0]   GTX1_TXPREEMPHASIS_IN,
    //--------------------- Transmit Ports - TX PLL Ports ----------------------
    input           GTX1_GTXTXRESET_IN,
    input           GTX1_MGTREFCLKTX_IN,
    input           GTX1_PLLTXRESET_IN,
    output          GTX1_TXPLLLKDET_OUT,
    output          GTX1_TXRESETDONE_OUT,
    //------------------- Transmit Ports - TX PRBS Generator -------------------
    input   [2:0]   GTX1_TXENPRBSTST_IN,
    input           GTX1_TXPRBSFORCEERR_IN,


    
    //_________________________________________________________________________
    //_________________________________________________________________________
    //GTX2  (X0Y2)

    //---------------------- Loopback and Powerdown Ports ----------------------
    input   [2:0]   GTX2_LOOPBACK_IN,
    //------------- Receive Ports - Comma Detection and Alignment --------------
    output          GTX2_RXCOMMADET_OUT,
    input           GTX2_RXSLIDE_IN,
    //--------------------- Receive Ports - PRBS Detection ---------------------
    input           GTX2_PRBSCNTRESET_IN,
    input   [2:0]   GTX2_RXENPRBSTST_IN,
    output          GTX2_RXPRBSERR_OUT,
    //----------------- Receive Ports - RX Data Path interface -----------------
    output  [19:0]  GTX2_RXDATA_OUT,
    input           GTX2_RXUSRCLK2_IN,
    //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
    input   [2:0]   GTX2_RXEQMIX_IN,
    input           GTX2_RXN_IN,
    input           GTX2_RXP_IN,
    //---------------------- Receive Ports - RX PLL Ports ----------------------
    input           GTX2_GTXRXRESET_IN,
    input           GTX2_MGTREFCLKRX_IN,
    input           GTX2_PLLRXRESET_IN,
    output          GTX2_RXPLLLKDET_OUT,
    output          GTX2_RXRESETDONE_OUT,
    //---------------- Transmit Ports - TX Data Path interface -----------------
    input   [19:0]  GTX2_TXDATA_IN,
    output          GTX2_TXOUTCLK_OUT,
    input           GTX2_TXUSRCLK2_IN,
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
    input   [3:0]   GTX2_TXDIFFCTRL_IN,
    output          GTX2_TXN_OUT,
    output          GTX2_TXP_OUT,
    input   [4:0]   GTX2_TXPOSTEMPHASIS_IN,
    //------------- Transmit Ports - TX Driver and OOB signalling --------------
    input   [3:0]   GTX2_TXPREEMPHASIS_IN,
    //--------------------- Transmit Ports - TX PLL Ports ----------------------
    input           GTX2_GTXTXRESET_IN,
    input           GTX2_MGTREFCLKTX_IN,
    input           GTX2_PLLTXRESET_IN,
    output          GTX2_TXPLLLKDET_OUT,
    output          GTX2_TXRESETDONE_OUT,
    //------------------- Transmit Ports - TX PRBS Generator -------------------
    input   [2:0]   GTX2_TXENPRBSTST_IN,
    input           GTX2_TXPRBSFORCEERR_IN,


    
    //_________________________________________________________________________
    //_________________________________________________________________________
    //GTX3  (X0Y3)

    //---------------------- Loopback and Powerdown Ports ----------------------
    input   [2:0]   GTX3_LOOPBACK_IN,
    //------------- Receive Ports - Comma Detection and Alignment --------------
    output          GTX3_RXCOMMADET_OUT,
    input           GTX3_RXSLIDE_IN,
    //--------------------- Receive Ports - PRBS Detection ---------------------
    input           GTX3_PRBSCNTRESET_IN,
    input   [2:0]   GTX3_RXENPRBSTST_IN,
    output          GTX3_RXPRBSERR_OUT,
    //----------------- Receive Ports - RX Data Path interface -----------------
    output  [19:0]  GTX3_RXDATA_OUT,
    input           GTX3_RXUSRCLK2_IN,
    //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
    input   [2:0]   GTX3_RXEQMIX_IN,
    input           GTX3_RXN_IN,
    input           GTX3_RXP_IN,
    //---------------------- Receive Ports - RX PLL Ports ----------------------
    input           GTX3_GTXRXRESET_IN,
    input           GTX3_MGTREFCLKRX_IN,
    input           GTX3_PLLRXRESET_IN,
    output          GTX3_RXPLLLKDET_OUT,
    output          GTX3_RXRESETDONE_OUT,
    //---------------- Transmit Ports - TX Data Path interface -----------------
    input   [19:0]  GTX3_TXDATA_IN,
    output          GTX3_TXOUTCLK_OUT,
    input           GTX3_TXUSRCLK2_IN,
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
    input   [3:0]   GTX3_TXDIFFCTRL_IN,
    output          GTX3_TXN_OUT,
    output          GTX3_TXP_OUT,
    input   [4:0]   GTX3_TXPOSTEMPHASIS_IN,
    //------------- Transmit Ports - TX Driver and OOB signalling --------------
    input   [3:0]   GTX3_TXPREEMPHASIS_IN,
    //--------------------- Transmit Ports - TX PLL Ports ----------------------
    input           GTX3_GTXTXRESET_IN,
    input           GTX3_MGTREFCLKTX_IN,
    input           GTX3_PLLTXRESET_IN,
    output          GTX3_TXPLLLKDET_OUT,
    output          GTX3_TXRESETDONE_OUT,
    //------------------- Transmit Ports - TX PRBS Generator -------------------
    input   [2:0]   GTX3_TXENPRBSTST_IN,
    input           GTX3_TXPRBSFORCEERR_IN,


    
    //_________________________________________________________________________
    //_________________________________________________________________________
    //GTX4  (X0Y4)

    //---------------------- Loopback and Powerdown Ports ----------------------
    input   [2:0]   GTX4_LOOPBACK_IN,
    //------------- Receive Ports - Comma Detection and Alignment --------------
    output          GTX4_RXCOMMADET_OUT,
    input           GTX4_RXSLIDE_IN,
    //--------------------- Receive Ports - PRBS Detection ---------------------
    input           GTX4_PRBSCNTRESET_IN,
    input   [2:0]   GTX4_RXENPRBSTST_IN,
    output          GTX4_RXPRBSERR_OUT,
    //----------------- Receive Ports - RX Data Path interface -----------------
    output  [19:0]  GTX4_RXDATA_OUT,
    input           GTX4_RXUSRCLK2_IN,
    //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
    input   [2:0]   GTX4_RXEQMIX_IN,
    input           GTX4_RXN_IN,
    input           GTX4_RXP_IN,
    //---------------------- Receive Ports - RX PLL Ports ----------------------
    input           GTX4_GTXRXRESET_IN,
    input           GTX4_MGTREFCLKRX_IN,
    input           GTX4_PLLRXRESET_IN,
    output          GTX4_RXPLLLKDET_OUT,
    output          GTX4_RXRESETDONE_OUT,
    //---------------- Transmit Ports - TX Data Path interface -----------------
    input   [19:0]  GTX4_TXDATA_IN,
    output          GTX4_TXOUTCLK_OUT,
    input           GTX4_TXUSRCLK2_IN,
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
    input   [3:0]   GTX4_TXDIFFCTRL_IN,
    output          GTX4_TXN_OUT,
    output          GTX4_TXP_OUT,
    input   [4:0]   GTX4_TXPOSTEMPHASIS_IN,
    //------------- Transmit Ports - TX Driver and OOB signalling --------------
    input   [3:0]   GTX4_TXPREEMPHASIS_IN,
    //--------------------- Transmit Ports - TX PLL Ports ----------------------
    input           GTX4_GTXTXRESET_IN,
    input           GTX4_MGTREFCLKTX_IN,
    input           GTX4_PLLTXRESET_IN,
    output          GTX4_TXPLLLKDET_OUT,
    output          GTX4_TXRESETDONE_OUT,
    //------------------- Transmit Ports - TX PRBS Generator -------------------
    input   [2:0]   GTX4_TXENPRBSTST_IN,
    input           GTX4_TXPRBSFORCEERR_IN,


    
    //_________________________________________________________________________
    //_________________________________________________________________________
    //GTX5  (X0Y5)

    //---------------------- Loopback and Powerdown Ports ----------------------
    input   [2:0]   GTX5_LOOPBACK_IN,
    //------------- Receive Ports - Comma Detection and Alignment --------------
    output          GTX5_RXCOMMADET_OUT,
    input           GTX5_RXSLIDE_IN,
    //--------------------- Receive Ports - PRBS Detection ---------------------
    input           GTX5_PRBSCNTRESET_IN,
    input   [2:0]   GTX5_RXENPRBSTST_IN,
    output          GTX5_RXPRBSERR_OUT,
    //----------------- Receive Ports - RX Data Path interface -----------------
    output  [19:0]  GTX5_RXDATA_OUT,
    input           GTX5_RXUSRCLK2_IN,
    //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
    input   [2:0]   GTX5_RXEQMIX_IN,
    input           GTX5_RXN_IN,
    input           GTX5_RXP_IN,
    //---------------------- Receive Ports - RX PLL Ports ----------------------
    input           GTX5_GTXRXRESET_IN,
    input           GTX5_MGTREFCLKRX_IN,
    input           GTX5_PLLRXRESET_IN,
    output          GTX5_RXPLLLKDET_OUT,
    output          GTX5_RXRESETDONE_OUT,
    //---------------- Transmit Ports - TX Data Path interface -----------------
    input   [19:0]  GTX5_TXDATA_IN,
    output          GTX5_TXOUTCLK_OUT,
    input           GTX5_TXUSRCLK2_IN,
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
    input   [3:0]   GTX5_TXDIFFCTRL_IN,
    output          GTX5_TXN_OUT,
    output          GTX5_TXP_OUT,
    input   [4:0]   GTX5_TXPOSTEMPHASIS_IN,
    //------------- Transmit Ports - TX Driver and OOB signalling --------------
    input   [3:0]   GTX5_TXPREEMPHASIS_IN,
    //--------------------- Transmit Ports - TX PLL Ports ----------------------
    input           GTX5_GTXTXRESET_IN,
    input           GTX5_MGTREFCLKTX_IN,
    input           GTX5_PLLTXRESET_IN,
    output          GTX5_TXPLLLKDET_OUT,
    output          GTX5_TXRESETDONE_OUT,
    //------------------- Transmit Ports - TX PRBS Generator -------------------
    input   [2:0]   GTX5_TXENPRBSTST_IN,
    input           GTX5_TXPRBSFORCEERR_IN,


    
    //_________________________________________________________________________
    //_________________________________________________________________________
    //GTX6  (X0Y6)

    //---------------------- Loopback and Powerdown Ports ----------------------
    input   [2:0]   GTX6_LOOPBACK_IN,
    //------------- Receive Ports - Comma Detection and Alignment --------------
    output          GTX6_RXCOMMADET_OUT,
    input           GTX6_RXSLIDE_IN,
    //--------------------- Receive Ports - PRBS Detection ---------------------
    input           GTX6_PRBSCNTRESET_IN,
    input   [2:0]   GTX6_RXENPRBSTST_IN,
    output          GTX6_RXPRBSERR_OUT,
    //----------------- Receive Ports - RX Data Path interface -----------------
    output  [19:0]  GTX6_RXDATA_OUT,
    input           GTX6_RXUSRCLK2_IN,
    //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
    input   [2:0]   GTX6_RXEQMIX_IN,
    input           GTX6_RXN_IN,
    input           GTX6_RXP_IN,
    //---------------------- Receive Ports - RX PLL Ports ----------------------
    input           GTX6_GTXRXRESET_IN,
    input           GTX6_MGTREFCLKRX_IN,
    input           GTX6_PLLRXRESET_IN,
    output          GTX6_RXPLLLKDET_OUT,
    output          GTX6_RXRESETDONE_OUT,
    //---------------- Transmit Ports - TX Data Path interface -----------------
    input   [19:0]  GTX6_TXDATA_IN,
    output          GTX6_TXOUTCLK_OUT,
    input           GTX6_TXUSRCLK2_IN,
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
    input   [3:0]   GTX6_TXDIFFCTRL_IN,
    output          GTX6_TXN_OUT,
    output          GTX6_TXP_OUT,
    input   [4:0]   GTX6_TXPOSTEMPHASIS_IN,
    //------------- Transmit Ports - TX Driver and OOB signalling --------------
    input   [3:0]   GTX6_TXPREEMPHASIS_IN,
    //--------------------- Transmit Ports - TX PLL Ports ----------------------
    input           GTX6_GTXTXRESET_IN,
    input           GTX6_MGTREFCLKTX_IN,
    input           GTX6_PLLTXRESET_IN,
    output          GTX6_TXPLLLKDET_OUT,
    output          GTX6_TXRESETDONE_OUT,
    //------------------- Transmit Ports - TX PRBS Generator -------------------
    input   [2:0]   GTX6_TXENPRBSTST_IN,
    input           GTX6_TXPRBSFORCEERR_IN,


    
    //_________________________________________________________________________
    //_________________________________________________________________________
    //GTX7  (X0Y7)

    //---------------------- Loopback and Powerdown Ports ----------------------
    input   [2:0]   GTX7_LOOPBACK_IN,
    //------------- Receive Ports - Comma Detection and Alignment --------------
    output          GTX7_RXCOMMADET_OUT,
    input           GTX7_RXSLIDE_IN,
    //--------------------- Receive Ports - PRBS Detection ---------------------
    input           GTX7_PRBSCNTRESET_IN,
    input   [2:0]   GTX7_RXENPRBSTST_IN,
    output          GTX7_RXPRBSERR_OUT,
    //----------------- Receive Ports - RX Data Path interface -----------------
    output  [19:0]  GTX7_RXDATA_OUT,
    input           GTX7_RXUSRCLK2_IN,
    //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
    input   [2:0]   GTX7_RXEQMIX_IN,
    input           GTX7_RXN_IN,
    input           GTX7_RXP_IN,
    //---------------------- Receive Ports - RX PLL Ports ----------------------
    input           GTX7_GTXRXRESET_IN,
    input           GTX7_MGTREFCLKRX_IN,
    input           GTX7_PLLRXRESET_IN,
    output          GTX7_RXPLLLKDET_OUT,
    output          GTX7_RXRESETDONE_OUT,
    //---------------- Transmit Ports - TX Data Path interface -----------------
    input   [19:0]  GTX7_TXDATA_IN,
    output          GTX7_TXOUTCLK_OUT,
    input           GTX7_TXUSRCLK2_IN,
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
    input   [3:0]   GTX7_TXDIFFCTRL_IN,
    output          GTX7_TXN_OUT,
    output          GTX7_TXP_OUT,
    input   [4:0]   GTX7_TXPOSTEMPHASIS_IN,
    //------------- Transmit Ports - TX Driver and OOB signalling --------------
    input   [3:0]   GTX7_TXPREEMPHASIS_IN,
    //--------------------- Transmit Ports - TX PLL Ports ----------------------
    input           GTX7_GTXTXRESET_IN,
    input           GTX7_MGTREFCLKTX_IN,
    input           GTX7_PLLTXRESET_IN,
    output          GTX7_TXPLLLKDET_OUT,
    output          GTX7_TXRESETDONE_OUT,
    //------------------- Transmit Ports - TX PRBS Generator -------------------
    input   [2:0]   GTX7_TXENPRBSTST_IN,
    input           GTX7_TXPRBSFORCEERR_IN,


    
    //_________________________________________________________________________
    //_________________________________________________________________________
    //GTX8  (X0Y8)

    //---------------------- Loopback and Powerdown Ports ----------------------
    input   [2:0]   GTX8_LOOPBACK_IN,
    //------------- Receive Ports - Comma Detection and Alignment --------------
    output          GTX8_RXCOMMADET_OUT,
    input           GTX8_RXSLIDE_IN,
    //--------------------- Receive Ports - PRBS Detection ---------------------
    input           GTX8_PRBSCNTRESET_IN,
    input   [2:0]   GTX8_RXENPRBSTST_IN,
    output          GTX8_RXPRBSERR_OUT,
    //----------------- Receive Ports - RX Data Path interface -----------------
    output  [19:0]  GTX8_RXDATA_OUT,
    input           GTX8_RXUSRCLK2_IN,
    //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
    input   [2:0]   GTX8_RXEQMIX_IN,
    input           GTX8_RXN_IN,
    input           GTX8_RXP_IN,
    //---------------------- Receive Ports - RX PLL Ports ----------------------
    input           GTX8_GTXRXRESET_IN,
    input           GTX8_MGTREFCLKRX_IN,
    input           GTX8_PLLRXRESET_IN,
    output          GTX8_RXPLLLKDET_OUT,
    output          GTX8_RXRESETDONE_OUT,
    //---------------- Transmit Ports - TX Data Path interface -----------------
    input   [19:0]  GTX8_TXDATA_IN,
    output          GTX8_TXOUTCLK_OUT,
    input           GTX8_TXUSRCLK2_IN,
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
    input   [3:0]   GTX8_TXDIFFCTRL_IN,
    output          GTX8_TXN_OUT,
    output          GTX8_TXP_OUT,
    input   [4:0]   GTX8_TXPOSTEMPHASIS_IN,
    //------------- Transmit Ports - TX Driver and OOB signalling --------------
    input   [3:0]   GTX8_TXPREEMPHASIS_IN,
    //--------------------- Transmit Ports - TX PLL Ports ----------------------
    input           GTX8_GTXTXRESET_IN,
    input           GTX8_MGTREFCLKTX_IN,
    input           GTX8_PLLTXRESET_IN,
    output          GTX8_TXPLLLKDET_OUT,
    output          GTX8_TXRESETDONE_OUT,
    //------------------- Transmit Ports - TX PRBS Generator -------------------
    input   [2:0]   GTX8_TXENPRBSTST_IN,
    input           GTX8_TXPRBSFORCEERR_IN,


    
    //_________________________________________________________________________
    //_________________________________________________________________________
    //GTX9  (X0Y9)

    //---------------------- Loopback and Powerdown Ports ----------------------
    input   [2:0]   GTX9_LOOPBACK_IN,
    //------------- Receive Ports - Comma Detection and Alignment --------------
    output          GTX9_RXCOMMADET_OUT,
    input           GTX9_RXSLIDE_IN,
    //--------------------- Receive Ports - PRBS Detection ---------------------
    input           GTX9_PRBSCNTRESET_IN,
    input   [2:0]   GTX9_RXENPRBSTST_IN,
    output          GTX9_RXPRBSERR_OUT,
    //----------------- Receive Ports - RX Data Path interface -----------------
    output  [19:0]  GTX9_RXDATA_OUT,
    input           GTX9_RXUSRCLK2_IN,
    //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
    input   [2:0]   GTX9_RXEQMIX_IN,
    input           GTX9_RXN_IN,
    input           GTX9_RXP_IN,
    //---------------------- Receive Ports - RX PLL Ports ----------------------
    input           GTX9_GTXRXRESET_IN,
    input           GTX9_MGTREFCLKRX_IN,
    input           GTX9_PLLRXRESET_IN,
    output          GTX9_RXPLLLKDET_OUT,
    output          GTX9_RXRESETDONE_OUT,
    //---------------- Transmit Ports - TX Data Path interface -----------------
    input   [19:0]  GTX9_TXDATA_IN,
    output          GTX9_TXOUTCLK_OUT,
    input           GTX9_TXUSRCLK2_IN,
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
    input   [3:0]   GTX9_TXDIFFCTRL_IN,
    output          GTX9_TXN_OUT,
    output          GTX9_TXP_OUT,
    input   [4:0]   GTX9_TXPOSTEMPHASIS_IN,
    //------------- Transmit Ports - TX Driver and OOB signalling --------------
    input   [3:0]   GTX9_TXPREEMPHASIS_IN,
    //--------------------- Transmit Ports - TX PLL Ports ----------------------
    input           GTX9_GTXTXRESET_IN,
    input           GTX9_MGTREFCLKTX_IN,
    input           GTX9_PLLTXRESET_IN,
    output          GTX9_TXPLLLKDET_OUT,
    output          GTX9_TXRESETDONE_OUT,
    //------------------- Transmit Ports - TX PRBS Generator -------------------
    input   [2:0]   GTX9_TXENPRBSTST_IN,
    input           GTX9_TXPRBSFORCEERR_IN,


    
    //_________________________________________________________________________
    //_________________________________________________________________________
    //GTX10  (X0Y10)

    //---------------------- Loopback and Powerdown Ports ----------------------
    input   [2:0]   GTX10_LOOPBACK_IN,
    //------------- Receive Ports - Comma Detection and Alignment --------------
    output          GTX10_RXCOMMADET_OUT,
    input           GTX10_RXSLIDE_IN,
    //--------------------- Receive Ports - PRBS Detection ---------------------
    input           GTX10_PRBSCNTRESET_IN,
    input   [2:0]   GTX10_RXENPRBSTST_IN,
    output          GTX10_RXPRBSERR_OUT,
    //----------------- Receive Ports - RX Data Path interface -----------------
    output  [19:0]  GTX10_RXDATA_OUT,
    input           GTX10_RXUSRCLK2_IN,
    //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
    input   [2:0]   GTX10_RXEQMIX_IN,
    input           GTX10_RXN_IN,
    input           GTX10_RXP_IN,
    //---------------------- Receive Ports - RX PLL Ports ----------------------
    input           GTX10_GTXRXRESET_IN,
    input           GTX10_MGTREFCLKRX_IN,
    input           GTX10_PLLRXRESET_IN,
    output          GTX10_RXPLLLKDET_OUT,
    output          GTX10_RXRESETDONE_OUT,
    //---------------- Transmit Ports - TX Data Path interface -----------------
    input   [19:0]  GTX10_TXDATA_IN,
    output          GTX10_TXOUTCLK_OUT,
    input           GTX10_TXUSRCLK2_IN,
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
    input   [3:0]   GTX10_TXDIFFCTRL_IN,
    output          GTX10_TXN_OUT,
    output          GTX10_TXP_OUT,
    input   [4:0]   GTX10_TXPOSTEMPHASIS_IN,
    //------------- Transmit Ports - TX Driver and OOB signalling --------------
    input   [3:0]   GTX10_TXPREEMPHASIS_IN,
    //--------------------- Transmit Ports - TX PLL Ports ----------------------
    input           GTX10_GTXTXRESET_IN,
    input           GTX10_MGTREFCLKTX_IN,
    input           GTX10_PLLTXRESET_IN,
    output          GTX10_TXPLLLKDET_OUT,
    output          GTX10_TXRESETDONE_OUT,
    //------------------- Transmit Ports - TX PRBS Generator -------------------
    input   [2:0]   GTX10_TXENPRBSTST_IN,
    input           GTX10_TXPRBSFORCEERR_IN,


    
    //_________________________________________________________________________
    //_________________________________________________________________________
    //GTX11  (X0Y11)

    //---------------------- Loopback and Powerdown Ports ----------------------
    input   [2:0]   GTX11_LOOPBACK_IN,
    //------------- Receive Ports - Comma Detection and Alignment --------------
    output          GTX11_RXCOMMADET_OUT,
    input           GTX11_RXSLIDE_IN,
    //--------------------- Receive Ports - PRBS Detection ---------------------
    input           GTX11_PRBSCNTRESET_IN,
    input   [2:0]   GTX11_RXENPRBSTST_IN,
    output          GTX11_RXPRBSERR_OUT,
    //----------------- Receive Ports - RX Data Path interface -----------------
    output  [19:0]  GTX11_RXDATA_OUT,
    input           GTX11_RXUSRCLK2_IN,
    //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
    input   [2:0]   GTX11_RXEQMIX_IN,
    input           GTX11_RXN_IN,
    input           GTX11_RXP_IN,
    //---------------------- Receive Ports - RX PLL Ports ----------------------
    input           GTX11_GTXRXRESET_IN,
    input           GTX11_MGTREFCLKRX_IN,
    input           GTX11_PLLRXRESET_IN,
    output          GTX11_RXPLLLKDET_OUT,
    output          GTX11_RXRESETDONE_OUT,
    //---------------- Transmit Ports - TX Data Path interface -----------------
    input   [19:0]  GTX11_TXDATA_IN,
    output          GTX11_TXOUTCLK_OUT,
    input           GTX11_TXUSRCLK2_IN,
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
    input   [3:0]   GTX11_TXDIFFCTRL_IN,
    output          GTX11_TXN_OUT,
    output          GTX11_TXP_OUT,
    input   [4:0]   GTX11_TXPOSTEMPHASIS_IN,
    //------------- Transmit Ports - TX Driver and OOB signalling --------------
    input   [3:0]   GTX11_TXPREEMPHASIS_IN,
    //--------------------- Transmit Ports - TX PLL Ports ----------------------
    input           GTX11_GTXTXRESET_IN,
    input           GTX11_MGTREFCLKTX_IN,
    input           GTX11_PLLTXRESET_IN,
    output          GTX11_TXPLLLKDET_OUT,
    output          GTX11_TXRESETDONE_OUT,
    //------------------- Transmit Ports - TX PRBS Generator -------------------
    input   [2:0]   GTX11_TXENPRBSTST_IN,
    input           GTX11_TXPRBSFORCEERR_IN


);

//***************************** Wire Declarations *****************************

    // ground and vcc signals
    wire            tied_to_ground_i;
    wire    [63:0]  tied_to_ground_vec_i;
    wire            tied_to_vcc_i;
    wire    [63:0]  tied_to_vcc_vec_i;
 
//********************************* Main Body of Code**************************

    assign tied_to_ground_i             = 1'b0;
    assign tied_to_ground_vec_i         = 64'h0000000000000000;
    assign tied_to_vcc_i                = 1'b1;
    assign tied_to_vcc_vec_i            = 64'hffffffffffffffff;


//------------------------- GTX Instances  -------------------------------



    //_________________________________________________________________________
    //_________________________________________________________________________
    //GTX0  (X0Y0)

    Gem_firefly_gtx #
    (
        // Simulation attributes
        .GTX_SIM_GTXRESET_SPEEDUP   (WRAPPER_SIM_GTXRESET_SPEEDUP),
        
        // Share RX PLL parameter
        .GTX_TX_CLK_SOURCE           ("TXPLL"),
        // Save power parameter
        .GTX_POWER_SAVE              (10'b0000110000)
    )
    gtx0_Gem_firefly_i
    (
        //---------------------- Loopback and Powerdown Ports ----------------------
        .LOOPBACK_IN                    (GTX0_LOOPBACK_IN),
        //------------- Receive Ports - Comma Detection and Alignment --------------
        .RXCOMMADET_OUT                 (GTX0_RXCOMMADET_OUT),
        .RXSLIDE_IN                     (GTX0_RXSLIDE_IN),
        //--------------------- Receive Ports - PRBS Detection ---------------------
        .PRBSCNTRESET_IN                (GTX0_PRBSCNTRESET_IN),
        .RXENPRBSTST_IN                 (GTX0_RXENPRBSTST_IN),
        .RXPRBSERR_OUT                  (GTX0_RXPRBSERR_OUT),
        //----------------- Receive Ports - RX Data Path interface -----------------
        .RXDATA_OUT                     (GTX0_RXDATA_OUT),
        .RXUSRCLK2_IN                   (GTX0_RXUSRCLK2_IN),
        //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
        .RXEQMIX_IN                     (GTX0_RXEQMIX_IN),
        .RXN_IN                         (GTX0_RXN_IN),
        .RXP_IN                         (GTX0_RXP_IN),
        //---------------------- Receive Ports - RX PLL Ports ----------------------
        .GTXRXRESET_IN                  (GTX0_GTXRXRESET_IN),
        .MGTREFCLKRX_IN                 ({tied_to_ground_i , GTX0_MGTREFCLKRX_IN}),
        .PLLRXRESET_IN                  (GTX0_PLLRXRESET_IN),
        .RXPLLLKDET_OUT                 (GTX0_RXPLLLKDET_OUT),
        .RXRESETDONE_OUT                (GTX0_RXRESETDONE_OUT),
        //---------------- Transmit Ports - TX Data Path interface -----------------
        .TXDATA_IN                      (GTX0_TXDATA_IN),
        .TXOUTCLK_OUT                   (GTX0_TXOUTCLK_OUT),
        .TXUSRCLK2_IN                   (GTX0_TXUSRCLK2_IN),
        //-------------- Transmit Ports - TX Driver and OOB signaling --------------
        .TXDIFFCTRL_IN                  (GTX0_TXDIFFCTRL_IN),
        .TXN_OUT                        (GTX0_TXN_OUT),
        .TXP_OUT                        (GTX0_TXP_OUT),
        .TXPOSTEMPHASIS_IN              (GTX0_TXPOSTEMPHASIS_IN),
        //------------- Transmit Ports - TX Driver and OOB signalling --------------
        .TXPREEMPHASIS_IN               (GTX0_TXPREEMPHASIS_IN),
        //--------------------- Transmit Ports - TX PLL Ports ----------------------
        .GTXTXRESET_IN                  (GTX0_GTXTXRESET_IN),
        .MGTREFCLKTX_IN                 ({tied_to_ground_i , GTX0_MGTREFCLKTX_IN}),
        .PLLTXRESET_IN                  (GTX0_PLLTXRESET_IN),
        .TXPLLLKDET_OUT                 (GTX0_TXPLLLKDET_OUT),
        .TXRESETDONE_OUT                (GTX0_TXRESETDONE_OUT),
        //------------------- Transmit Ports - TX PRBS Generator -------------------
        .TXENPRBSTST_IN                 (GTX0_TXENPRBSTST_IN),
        .TXPRBSFORCEERR_IN              (GTX0_TXPRBSFORCEERR_IN)

    );



    //_________________________________________________________________________
    //_________________________________________________________________________
    //GTX1  (X0Y1)

    Gem_firefly_gtx #
    (
        // Simulation attributes
        .GTX_SIM_GTXRESET_SPEEDUP   (WRAPPER_SIM_GTXRESET_SPEEDUP),
        
        // Share RX PLL parameter
        .GTX_TX_CLK_SOURCE           ("TXPLL"),
        // Save power parameter
        .GTX_POWER_SAVE              (10'b0000110000)
    )
    gtx1_Gem_firefly_i
    (
        //---------------------- Loopback and Powerdown Ports ----------------------
        .LOOPBACK_IN                    (GTX1_LOOPBACK_IN),
        //------------- Receive Ports - Comma Detection and Alignment --------------
        .RXCOMMADET_OUT                 (GTX1_RXCOMMADET_OUT),
        .RXSLIDE_IN                     (GTX1_RXSLIDE_IN),
        //--------------------- Receive Ports - PRBS Detection ---------------------
        .PRBSCNTRESET_IN                (GTX1_PRBSCNTRESET_IN),
        .RXENPRBSTST_IN                 (GTX1_RXENPRBSTST_IN),
        .RXPRBSERR_OUT                  (GTX1_RXPRBSERR_OUT),
        //----------------- Receive Ports - RX Data Path interface -----------------
        .RXDATA_OUT                     (GTX1_RXDATA_OUT),
        .RXUSRCLK2_IN                   (GTX1_RXUSRCLK2_IN),
        //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
        .RXEQMIX_IN                     (GTX1_RXEQMIX_IN),
        .RXN_IN                         (GTX1_RXN_IN),
        .RXP_IN                         (GTX1_RXP_IN),
        //---------------------- Receive Ports - RX PLL Ports ----------------------
        .GTXRXRESET_IN                  (GTX1_GTXRXRESET_IN),
        .MGTREFCLKRX_IN                 ({tied_to_ground_i , GTX1_MGTREFCLKRX_IN}),
        .PLLRXRESET_IN                  (GTX1_PLLRXRESET_IN),
        .RXPLLLKDET_OUT                 (GTX1_RXPLLLKDET_OUT),
        .RXRESETDONE_OUT                (GTX1_RXRESETDONE_OUT),
        //---------------- Transmit Ports - TX Data Path interface -----------------
        .TXDATA_IN                      (GTX1_TXDATA_IN),
        .TXOUTCLK_OUT                   (GTX1_TXOUTCLK_OUT),
        .TXUSRCLK2_IN                   (GTX1_TXUSRCLK2_IN),
        //-------------- Transmit Ports - TX Driver and OOB signaling --------------
        .TXDIFFCTRL_IN                  (GTX1_TXDIFFCTRL_IN),
        .TXN_OUT                        (GTX1_TXN_OUT),
        .TXP_OUT                        (GTX1_TXP_OUT),
        .TXPOSTEMPHASIS_IN              (GTX1_TXPOSTEMPHASIS_IN),
        //------------- Transmit Ports - TX Driver and OOB signalling --------------
        .TXPREEMPHASIS_IN               (GTX1_TXPREEMPHASIS_IN),
        //--------------------- Transmit Ports - TX PLL Ports ----------------------
        .GTXTXRESET_IN                  (GTX1_GTXTXRESET_IN),
        .MGTREFCLKTX_IN                 ({tied_to_ground_i , GTX1_MGTREFCLKTX_IN}),
        .PLLTXRESET_IN                  (GTX1_PLLTXRESET_IN),
        .TXPLLLKDET_OUT                 (GTX1_TXPLLLKDET_OUT),
        .TXRESETDONE_OUT                (GTX1_TXRESETDONE_OUT),
        //------------------- Transmit Ports - TX PRBS Generator -------------------
        .TXENPRBSTST_IN                 (GTX1_TXENPRBSTST_IN),
        .TXPRBSFORCEERR_IN              (GTX1_TXPRBSFORCEERR_IN)

    );



    //_________________________________________________________________________
    //_________________________________________________________________________
    //GTX2  (X0Y2)

    Gem_firefly_gtx #
    (
        // Simulation attributes
        .GTX_SIM_GTXRESET_SPEEDUP   (WRAPPER_SIM_GTXRESET_SPEEDUP),
        
        // Share RX PLL parameter
        .GTX_TX_CLK_SOURCE           ("TXPLL"),
        // Save power parameter
        .GTX_POWER_SAVE              (10'b0000110000)
    )
    gtx2_Gem_firefly_i
    (
        //---------------------- Loopback and Powerdown Ports ----------------------
        .LOOPBACK_IN                    (GTX2_LOOPBACK_IN),
        //------------- Receive Ports - Comma Detection and Alignment --------------
        .RXCOMMADET_OUT                 (GTX2_RXCOMMADET_OUT),
        .RXSLIDE_IN                     (GTX2_RXSLIDE_IN),
        //--------------------- Receive Ports - PRBS Detection ---------------------
        .PRBSCNTRESET_IN                (GTX2_PRBSCNTRESET_IN),
        .RXENPRBSTST_IN                 (GTX2_RXENPRBSTST_IN),
        .RXPRBSERR_OUT                  (GTX2_RXPRBSERR_OUT),
        //----------------- Receive Ports - RX Data Path interface -----------------
        .RXDATA_OUT                     (GTX2_RXDATA_OUT),
        .RXUSRCLK2_IN                   (GTX2_RXUSRCLK2_IN),
        //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
        .RXEQMIX_IN                     (GTX2_RXEQMIX_IN),
        .RXN_IN                         (GTX2_RXN_IN),
        .RXP_IN                         (GTX2_RXP_IN),
        //---------------------- Receive Ports - RX PLL Ports ----------------------
        .GTXRXRESET_IN                  (GTX2_GTXRXRESET_IN),
        .MGTREFCLKRX_IN                 ({tied_to_ground_i , GTX2_MGTREFCLKRX_IN}),
        .PLLRXRESET_IN                  (GTX2_PLLRXRESET_IN),
        .RXPLLLKDET_OUT                 (GTX2_RXPLLLKDET_OUT),
        .RXRESETDONE_OUT                (GTX2_RXRESETDONE_OUT),
        //---------------- Transmit Ports - TX Data Path interface -----------------
        .TXDATA_IN                      (GTX2_TXDATA_IN),
        .TXOUTCLK_OUT                   (GTX2_TXOUTCLK_OUT),
        .TXUSRCLK2_IN                   (GTX2_TXUSRCLK2_IN),
        //-------------- Transmit Ports - TX Driver and OOB signaling --------------
        .TXDIFFCTRL_IN                  (GTX2_TXDIFFCTRL_IN),
        .TXN_OUT                        (GTX2_TXN_OUT),
        .TXP_OUT                        (GTX2_TXP_OUT),
        .TXPOSTEMPHASIS_IN              (GTX2_TXPOSTEMPHASIS_IN),
        //------------- Transmit Ports - TX Driver and OOB signalling --------------
        .TXPREEMPHASIS_IN               (GTX2_TXPREEMPHASIS_IN),
        //--------------------- Transmit Ports - TX PLL Ports ----------------------
        .GTXTXRESET_IN                  (GTX2_GTXTXRESET_IN),
        .MGTREFCLKTX_IN                 ({tied_to_ground_i , GTX2_MGTREFCLKTX_IN}),
        .PLLTXRESET_IN                  (GTX2_PLLTXRESET_IN),
        .TXPLLLKDET_OUT                 (GTX2_TXPLLLKDET_OUT),
        .TXRESETDONE_OUT                (GTX2_TXRESETDONE_OUT),
        //------------------- Transmit Ports - TX PRBS Generator -------------------
        .TXENPRBSTST_IN                 (GTX2_TXENPRBSTST_IN),
        .TXPRBSFORCEERR_IN              (GTX2_TXPRBSFORCEERR_IN)

    );



    //_________________________________________________________________________
    //_________________________________________________________________________
    //GTX3  (X0Y3)

    Gem_firefly_gtx #
    (
        // Simulation attributes
        .GTX_SIM_GTXRESET_SPEEDUP   (WRAPPER_SIM_GTXRESET_SPEEDUP),
        
        // Share RX PLL parameter
        .GTX_TX_CLK_SOURCE           ("TXPLL"),
        // Save power parameter
        .GTX_POWER_SAVE              (10'b0000110000)
    )
    gtx3_Gem_firefly_i
    (
        //---------------------- Loopback and Powerdown Ports ----------------------
        .LOOPBACK_IN                    (GTX3_LOOPBACK_IN),
        //------------- Receive Ports - Comma Detection and Alignment --------------
        .RXCOMMADET_OUT                 (GTX3_RXCOMMADET_OUT),
        .RXSLIDE_IN                     (GTX3_RXSLIDE_IN),
        //--------------------- Receive Ports - PRBS Detection ---------------------
        .PRBSCNTRESET_IN                (GTX3_PRBSCNTRESET_IN),
        .RXENPRBSTST_IN                 (GTX3_RXENPRBSTST_IN),
        .RXPRBSERR_OUT                  (GTX3_RXPRBSERR_OUT),
        //----------------- Receive Ports - RX Data Path interface -----------------
        .RXDATA_OUT                     (GTX3_RXDATA_OUT),
        .RXUSRCLK2_IN                   (GTX3_RXUSRCLK2_IN),
        //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
        .RXEQMIX_IN                     (GTX3_RXEQMIX_IN),
        .RXN_IN                         (GTX3_RXN_IN),
        .RXP_IN                         (GTX3_RXP_IN),
        //---------------------- Receive Ports - RX PLL Ports ----------------------
        .GTXRXRESET_IN                  (GTX3_GTXRXRESET_IN),
        .MGTREFCLKRX_IN                 ({tied_to_ground_i , GTX3_MGTREFCLKRX_IN}),
        .PLLRXRESET_IN                  (GTX3_PLLRXRESET_IN),
        .RXPLLLKDET_OUT                 (GTX3_RXPLLLKDET_OUT),
        .RXRESETDONE_OUT                (GTX3_RXRESETDONE_OUT),
        //---------------- Transmit Ports - TX Data Path interface -----------------
        .TXDATA_IN                      (GTX3_TXDATA_IN),
        .TXOUTCLK_OUT                   (GTX3_TXOUTCLK_OUT),
        .TXUSRCLK2_IN                   (GTX3_TXUSRCLK2_IN),
        //-------------- Transmit Ports - TX Driver and OOB signaling --------------
        .TXDIFFCTRL_IN                  (GTX3_TXDIFFCTRL_IN),
        .TXN_OUT                        (GTX3_TXN_OUT),
        .TXP_OUT                        (GTX3_TXP_OUT),
        .TXPOSTEMPHASIS_IN              (GTX3_TXPOSTEMPHASIS_IN),
        //------------- Transmit Ports - TX Driver and OOB signalling --------------
        .TXPREEMPHASIS_IN               (GTX3_TXPREEMPHASIS_IN),
        //--------------------- Transmit Ports - TX PLL Ports ----------------------
        .GTXTXRESET_IN                  (GTX3_GTXTXRESET_IN),
        .MGTREFCLKTX_IN                 ({tied_to_ground_i , GTX3_MGTREFCLKTX_IN}),
        .PLLTXRESET_IN                  (GTX3_PLLTXRESET_IN),
        .TXPLLLKDET_OUT                 (GTX3_TXPLLLKDET_OUT),
        .TXRESETDONE_OUT                (GTX3_TXRESETDONE_OUT),
        //------------------- Transmit Ports - TX PRBS Generator -------------------
        .TXENPRBSTST_IN                 (GTX3_TXENPRBSTST_IN),
        .TXPRBSFORCEERR_IN              (GTX3_TXPRBSFORCEERR_IN)

    );



    //_________________________________________________________________________
    //_________________________________________________________________________
    //GTX4  (X0Y4)

    Gem_firefly_gtx #
    (
        // Simulation attributes
        .GTX_SIM_GTXRESET_SPEEDUP   (WRAPPER_SIM_GTXRESET_SPEEDUP),
        
        // Share RX PLL parameter
        .GTX_TX_CLK_SOURCE           ("TXPLL"),
        // Save power parameter
        .GTX_POWER_SAVE              (10'b0000110000)
    )
    gtx4_Gem_firefly_i
    (
        //---------------------- Loopback and Powerdown Ports ----------------------
        .LOOPBACK_IN                    (GTX4_LOOPBACK_IN),
        //------------- Receive Ports - Comma Detection and Alignment --------------
        .RXCOMMADET_OUT                 (GTX4_RXCOMMADET_OUT),
        .RXSLIDE_IN                     (GTX4_RXSLIDE_IN),
        //--------------------- Receive Ports - PRBS Detection ---------------------
        .PRBSCNTRESET_IN                (GTX4_PRBSCNTRESET_IN),
        .RXENPRBSTST_IN                 (GTX4_RXENPRBSTST_IN),
        .RXPRBSERR_OUT                  (GTX4_RXPRBSERR_OUT),
        //----------------- Receive Ports - RX Data Path interface -----------------
        .RXDATA_OUT                     (GTX4_RXDATA_OUT),
        .RXUSRCLK2_IN                   (GTX4_RXUSRCLK2_IN),
        //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
        .RXEQMIX_IN                     (GTX4_RXEQMIX_IN),
        .RXN_IN                         (GTX4_RXN_IN),
        .RXP_IN                         (GTX4_RXP_IN),
        //---------------------- Receive Ports - RX PLL Ports ----------------------
        .GTXRXRESET_IN                  (GTX4_GTXRXRESET_IN),
        .MGTREFCLKRX_IN                 ({tied_to_ground_i , GTX4_MGTREFCLKRX_IN}),
        .PLLRXRESET_IN                  (GTX4_PLLRXRESET_IN),
        .RXPLLLKDET_OUT                 (GTX4_RXPLLLKDET_OUT),
        .RXRESETDONE_OUT                (GTX4_RXRESETDONE_OUT),
        //---------------- Transmit Ports - TX Data Path interface -----------------
        .TXDATA_IN                      (GTX4_TXDATA_IN),
        .TXOUTCLK_OUT                   (GTX4_TXOUTCLK_OUT),
        .TXUSRCLK2_IN                   (GTX4_TXUSRCLK2_IN),
        //-------------- Transmit Ports - TX Driver and OOB signaling --------------
        .TXDIFFCTRL_IN                  (GTX4_TXDIFFCTRL_IN),
        .TXN_OUT                        (GTX4_TXN_OUT),
        .TXP_OUT                        (GTX4_TXP_OUT),
        .TXPOSTEMPHASIS_IN              (GTX4_TXPOSTEMPHASIS_IN),
        //------------- Transmit Ports - TX Driver and OOB signalling --------------
        .TXPREEMPHASIS_IN               (GTX4_TXPREEMPHASIS_IN),
        //--------------------- Transmit Ports - TX PLL Ports ----------------------
        .GTXTXRESET_IN                  (GTX4_GTXTXRESET_IN),
        .MGTREFCLKTX_IN                 ({tied_to_ground_i , GTX4_MGTREFCLKTX_IN}),
        .PLLTXRESET_IN                  (GTX4_PLLTXRESET_IN),
        .TXPLLLKDET_OUT                 (GTX4_TXPLLLKDET_OUT),
        .TXRESETDONE_OUT                (GTX4_TXRESETDONE_OUT),
        //------------------- Transmit Ports - TX PRBS Generator -------------------
        .TXENPRBSTST_IN                 (GTX4_TXENPRBSTST_IN),
        .TXPRBSFORCEERR_IN              (GTX4_TXPRBSFORCEERR_IN)

    );



    //_________________________________________________________________________
    //_________________________________________________________________________
    //GTX5  (X0Y5)

    Gem_firefly_gtx #
    (
        // Simulation attributes
        .GTX_SIM_GTXRESET_SPEEDUP   (WRAPPER_SIM_GTXRESET_SPEEDUP),
        
        // Share RX PLL parameter
        .GTX_TX_CLK_SOURCE           ("TXPLL"),
        // Save power parameter
        .GTX_POWER_SAVE              (10'b0000110000)
    )
    gtx5_Gem_firefly_i
    (
        //---------------------- Loopback and Powerdown Ports ----------------------
        .LOOPBACK_IN                    (GTX5_LOOPBACK_IN),
        //------------- Receive Ports - Comma Detection and Alignment --------------
        .RXCOMMADET_OUT                 (GTX5_RXCOMMADET_OUT),
        .RXSLIDE_IN                     (GTX5_RXSLIDE_IN),
        //--------------------- Receive Ports - PRBS Detection ---------------------
        .PRBSCNTRESET_IN                (GTX5_PRBSCNTRESET_IN),
        .RXENPRBSTST_IN                 (GTX5_RXENPRBSTST_IN),
        .RXPRBSERR_OUT                  (GTX5_RXPRBSERR_OUT),
        //----------------- Receive Ports - RX Data Path interface -----------------
        .RXDATA_OUT                     (GTX5_RXDATA_OUT),
        .RXUSRCLK2_IN                   (GTX5_RXUSRCLK2_IN),
        //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
        .RXEQMIX_IN                     (GTX5_RXEQMIX_IN),
        .RXN_IN                         (GTX5_RXN_IN),
        .RXP_IN                         (GTX5_RXP_IN),
        //---------------------- Receive Ports - RX PLL Ports ----------------------
        .GTXRXRESET_IN                  (GTX5_GTXRXRESET_IN),
        .MGTREFCLKRX_IN                 ({tied_to_ground_i , GTX5_MGTREFCLKRX_IN}),
        .PLLRXRESET_IN                  (GTX5_PLLRXRESET_IN),
        .RXPLLLKDET_OUT                 (GTX5_RXPLLLKDET_OUT),
        .RXRESETDONE_OUT                (GTX5_RXRESETDONE_OUT),
        //---------------- Transmit Ports - TX Data Path interface -----------------
        .TXDATA_IN                      (GTX5_TXDATA_IN),
        .TXOUTCLK_OUT                   (GTX5_TXOUTCLK_OUT),
        .TXUSRCLK2_IN                   (GTX5_TXUSRCLK2_IN),
        //-------------- Transmit Ports - TX Driver and OOB signaling --------------
        .TXDIFFCTRL_IN                  (GTX5_TXDIFFCTRL_IN),
        .TXN_OUT                        (GTX5_TXN_OUT),
        .TXP_OUT                        (GTX5_TXP_OUT),
        .TXPOSTEMPHASIS_IN              (GTX5_TXPOSTEMPHASIS_IN),
        //------------- Transmit Ports - TX Driver and OOB signalling --------------
        .TXPREEMPHASIS_IN               (GTX5_TXPREEMPHASIS_IN),
        //--------------------- Transmit Ports - TX PLL Ports ----------------------
        .GTXTXRESET_IN                  (GTX5_GTXTXRESET_IN),
        .MGTREFCLKTX_IN                 ({tied_to_ground_i , GTX5_MGTREFCLKTX_IN}),
        .PLLTXRESET_IN                  (GTX5_PLLTXRESET_IN),
        .TXPLLLKDET_OUT                 (GTX5_TXPLLLKDET_OUT),
        .TXRESETDONE_OUT                (GTX5_TXRESETDONE_OUT),
        //------------------- Transmit Ports - TX PRBS Generator -------------------
        .TXENPRBSTST_IN                 (GTX5_TXENPRBSTST_IN),
        .TXPRBSFORCEERR_IN              (GTX5_TXPRBSFORCEERR_IN)

    );



    //_________________________________________________________________________
    //_________________________________________________________________________
    //GTX6  (X0Y6)

    Gem_firefly_gtx #
    (
        // Simulation attributes
        .GTX_SIM_GTXRESET_SPEEDUP   (WRAPPER_SIM_GTXRESET_SPEEDUP),
        
        // Share RX PLL parameter
        .GTX_TX_CLK_SOURCE           ("TXPLL"),
        // Save power parameter
        .GTX_POWER_SAVE              (10'b0000110000)
    )
    gtx6_Gem_firefly_i
    (
        //---------------------- Loopback and Powerdown Ports ----------------------
        .LOOPBACK_IN                    (GTX6_LOOPBACK_IN),
        //------------- Receive Ports - Comma Detection and Alignment --------------
        .RXCOMMADET_OUT                 (GTX6_RXCOMMADET_OUT),
        .RXSLIDE_IN                     (GTX6_RXSLIDE_IN),
        //--------------------- Receive Ports - PRBS Detection ---------------------
        .PRBSCNTRESET_IN                (GTX6_PRBSCNTRESET_IN),
        .RXENPRBSTST_IN                 (GTX6_RXENPRBSTST_IN),
        .RXPRBSERR_OUT                  (GTX6_RXPRBSERR_OUT),
        //----------------- Receive Ports - RX Data Path interface -----------------
        .RXDATA_OUT                     (GTX6_RXDATA_OUT),
        .RXUSRCLK2_IN                   (GTX6_RXUSRCLK2_IN),
        //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
        .RXEQMIX_IN                     (GTX6_RXEQMIX_IN),
        .RXN_IN                         (GTX6_RXN_IN),
        .RXP_IN                         (GTX6_RXP_IN),
        //---------------------- Receive Ports - RX PLL Ports ----------------------
        .GTXRXRESET_IN                  (GTX6_GTXRXRESET_IN),
        .MGTREFCLKRX_IN                 ({tied_to_ground_i , GTX6_MGTREFCLKRX_IN}),
        .PLLRXRESET_IN                  (GTX6_PLLRXRESET_IN),
        .RXPLLLKDET_OUT                 (GTX6_RXPLLLKDET_OUT),
        .RXRESETDONE_OUT                (GTX6_RXRESETDONE_OUT),
        //---------------- Transmit Ports - TX Data Path interface -----------------
        .TXDATA_IN                      (GTX6_TXDATA_IN),
        .TXOUTCLK_OUT                   (GTX6_TXOUTCLK_OUT),
        .TXUSRCLK2_IN                   (GTX6_TXUSRCLK2_IN),
        //-------------- Transmit Ports - TX Driver and OOB signaling --------------
        .TXDIFFCTRL_IN                  (GTX6_TXDIFFCTRL_IN),
        .TXN_OUT                        (GTX6_TXN_OUT),
        .TXP_OUT                        (GTX6_TXP_OUT),
        .TXPOSTEMPHASIS_IN              (GTX6_TXPOSTEMPHASIS_IN),
        //------------- Transmit Ports - TX Driver and OOB signalling --------------
        .TXPREEMPHASIS_IN               (GTX6_TXPREEMPHASIS_IN),
        //--------------------- Transmit Ports - TX PLL Ports ----------------------
        .GTXTXRESET_IN                  (GTX6_GTXTXRESET_IN),
        .MGTREFCLKTX_IN                 ({tied_to_ground_i , GTX6_MGTREFCLKTX_IN}),
        .PLLTXRESET_IN                  (GTX6_PLLTXRESET_IN),
        .TXPLLLKDET_OUT                 (GTX6_TXPLLLKDET_OUT),
        .TXRESETDONE_OUT                (GTX6_TXRESETDONE_OUT),
        //------------------- Transmit Ports - TX PRBS Generator -------------------
        .TXENPRBSTST_IN                 (GTX6_TXENPRBSTST_IN),
        .TXPRBSFORCEERR_IN              (GTX6_TXPRBSFORCEERR_IN)

    );



    //_________________________________________________________________________
    //_________________________________________________________________________
    //GTX7  (X0Y7)

    Gem_firefly_gtx #
    (
        // Simulation attributes
        .GTX_SIM_GTXRESET_SPEEDUP   (WRAPPER_SIM_GTXRESET_SPEEDUP),
        
        // Share RX PLL parameter
        .GTX_TX_CLK_SOURCE           ("TXPLL"),
        // Save power parameter
        .GTX_POWER_SAVE              (10'b0000110000)
    )
    gtx7_Gem_firefly_i
    (
        //---------------------- Loopback and Powerdown Ports ----------------------
        .LOOPBACK_IN                    (GTX7_LOOPBACK_IN),
        //------------- Receive Ports - Comma Detection and Alignment --------------
        .RXCOMMADET_OUT                 (GTX7_RXCOMMADET_OUT),
        .RXSLIDE_IN                     (GTX7_RXSLIDE_IN),
        //--------------------- Receive Ports - PRBS Detection ---------------------
        .PRBSCNTRESET_IN                (GTX7_PRBSCNTRESET_IN),
        .RXENPRBSTST_IN                 (GTX7_RXENPRBSTST_IN),
        .RXPRBSERR_OUT                  (GTX7_RXPRBSERR_OUT),
        //----------------- Receive Ports - RX Data Path interface -----------------
        .RXDATA_OUT                     (GTX7_RXDATA_OUT),
        .RXUSRCLK2_IN                   (GTX7_RXUSRCLK2_IN),
        //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
        .RXEQMIX_IN                     (GTX7_RXEQMIX_IN),
        .RXN_IN                         (GTX7_RXN_IN),
        .RXP_IN                         (GTX7_RXP_IN),
        //---------------------- Receive Ports - RX PLL Ports ----------------------
        .GTXRXRESET_IN                  (GTX7_GTXRXRESET_IN),
        .MGTREFCLKRX_IN                 ({tied_to_ground_i , GTX7_MGTREFCLKRX_IN}),
        .PLLRXRESET_IN                  (GTX7_PLLRXRESET_IN),
        .RXPLLLKDET_OUT                 (GTX7_RXPLLLKDET_OUT),
        .RXRESETDONE_OUT                (GTX7_RXRESETDONE_OUT),
        //---------------- Transmit Ports - TX Data Path interface -----------------
        .TXDATA_IN                      (GTX7_TXDATA_IN),
        .TXOUTCLK_OUT                   (GTX7_TXOUTCLK_OUT),
        .TXUSRCLK2_IN                   (GTX7_TXUSRCLK2_IN),
        //-------------- Transmit Ports - TX Driver and OOB signaling --------------
        .TXDIFFCTRL_IN                  (GTX7_TXDIFFCTRL_IN),
        .TXN_OUT                        (GTX7_TXN_OUT),
        .TXP_OUT                        (GTX7_TXP_OUT),
        .TXPOSTEMPHASIS_IN              (GTX7_TXPOSTEMPHASIS_IN),
        //------------- Transmit Ports - TX Driver and OOB signalling --------------
        .TXPREEMPHASIS_IN               (GTX7_TXPREEMPHASIS_IN),
        //--------------------- Transmit Ports - TX PLL Ports ----------------------
        .GTXTXRESET_IN                  (GTX7_GTXTXRESET_IN),
        .MGTREFCLKTX_IN                 ({tied_to_ground_i , GTX7_MGTREFCLKTX_IN}),
        .PLLTXRESET_IN                  (GTX7_PLLTXRESET_IN),
        .TXPLLLKDET_OUT                 (GTX7_TXPLLLKDET_OUT),
        .TXRESETDONE_OUT                (GTX7_TXRESETDONE_OUT),
        //------------------- Transmit Ports - TX PRBS Generator -------------------
        .TXENPRBSTST_IN                 (GTX7_TXENPRBSTST_IN),
        .TXPRBSFORCEERR_IN              (GTX7_TXPRBSFORCEERR_IN)

    );



    //_________________________________________________________________________
    //_________________________________________________________________________
    //GTX8  (X0Y8)

    Gem_firefly_gtx #
    (
        // Simulation attributes
        .GTX_SIM_GTXRESET_SPEEDUP   (WRAPPER_SIM_GTXRESET_SPEEDUP),
        
        // Share RX PLL parameter
        .GTX_TX_CLK_SOURCE           ("TXPLL"),
        // Save power parameter
        .GTX_POWER_SAVE              (10'b0000110000)
    )
    gtx8_Gem_firefly_i
    (
        //---------------------- Loopback and Powerdown Ports ----------------------
        .LOOPBACK_IN                    (GTX8_LOOPBACK_IN),
        //------------- Receive Ports - Comma Detection and Alignment --------------
        .RXCOMMADET_OUT                 (GTX8_RXCOMMADET_OUT),
        .RXSLIDE_IN                     (GTX8_RXSLIDE_IN),
        //--------------------- Receive Ports - PRBS Detection ---------------------
        .PRBSCNTRESET_IN                (GTX8_PRBSCNTRESET_IN),
        .RXENPRBSTST_IN                 (GTX8_RXENPRBSTST_IN),
        .RXPRBSERR_OUT                  (GTX8_RXPRBSERR_OUT),
        //----------------- Receive Ports - RX Data Path interface -----------------
        .RXDATA_OUT                     (GTX8_RXDATA_OUT),
        .RXUSRCLK2_IN                   (GTX8_RXUSRCLK2_IN),
        //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
        .RXEQMIX_IN                     (GTX8_RXEQMIX_IN),
        .RXN_IN                         (GTX8_RXN_IN),
        .RXP_IN                         (GTX8_RXP_IN),
        //---------------------- Receive Ports - RX PLL Ports ----------------------
        .GTXRXRESET_IN                  (GTX8_GTXRXRESET_IN),
        .MGTREFCLKRX_IN                 ({tied_to_ground_i , GTX8_MGTREFCLKRX_IN}),
        .PLLRXRESET_IN                  (GTX8_PLLRXRESET_IN),
        .RXPLLLKDET_OUT                 (GTX8_RXPLLLKDET_OUT),
        .RXRESETDONE_OUT                (GTX8_RXRESETDONE_OUT),
        //---------------- Transmit Ports - TX Data Path interface -----------------
        .TXDATA_IN                      (GTX8_TXDATA_IN),
        .TXOUTCLK_OUT                   (GTX8_TXOUTCLK_OUT),
        .TXUSRCLK2_IN                   (GTX8_TXUSRCLK2_IN),
        //-------------- Transmit Ports - TX Driver and OOB signaling --------------
        .TXDIFFCTRL_IN                  (GTX8_TXDIFFCTRL_IN),
        .TXN_OUT                        (GTX8_TXN_OUT),
        .TXP_OUT                        (GTX8_TXP_OUT),
        .TXPOSTEMPHASIS_IN              (GTX8_TXPOSTEMPHASIS_IN),
        //------------- Transmit Ports - TX Driver and OOB signalling --------------
        .TXPREEMPHASIS_IN               (GTX8_TXPREEMPHASIS_IN),
        //--------------------- Transmit Ports - TX PLL Ports ----------------------
        .GTXTXRESET_IN                  (GTX8_GTXTXRESET_IN),
        .MGTREFCLKTX_IN                 ({tied_to_ground_i , GTX8_MGTREFCLKTX_IN}),
        .PLLTXRESET_IN                  (GTX8_PLLTXRESET_IN),
        .TXPLLLKDET_OUT                 (GTX8_TXPLLLKDET_OUT),
        .TXRESETDONE_OUT                (GTX8_TXRESETDONE_OUT),
        //------------------- Transmit Ports - TX PRBS Generator -------------------
        .TXENPRBSTST_IN                 (GTX8_TXENPRBSTST_IN),
        .TXPRBSFORCEERR_IN              (GTX8_TXPRBSFORCEERR_IN)

    );



    //_________________________________________________________________________
    //_________________________________________________________________________
    //GTX9  (X0Y9)

    Gem_firefly_gtx #
    (
        // Simulation attributes
        .GTX_SIM_GTXRESET_SPEEDUP   (WRAPPER_SIM_GTXRESET_SPEEDUP),
        
        // Share RX PLL parameter
        .GTX_TX_CLK_SOURCE           ("TXPLL"),
        // Save power parameter
        .GTX_POWER_SAVE              (10'b0000110000)
    )
    gtx9_Gem_firefly_i
    (
        //---------------------- Loopback and Powerdown Ports ----------------------
        .LOOPBACK_IN                    (GTX9_LOOPBACK_IN),
        //------------- Receive Ports - Comma Detection and Alignment --------------
        .RXCOMMADET_OUT                 (GTX9_RXCOMMADET_OUT),
        .RXSLIDE_IN                     (GTX9_RXSLIDE_IN),
        //--------------------- Receive Ports - PRBS Detection ---------------------
        .PRBSCNTRESET_IN                (GTX9_PRBSCNTRESET_IN),
        .RXENPRBSTST_IN                 (GTX9_RXENPRBSTST_IN),
        .RXPRBSERR_OUT                  (GTX9_RXPRBSERR_OUT),
        //----------------- Receive Ports - RX Data Path interface -----------------
        .RXDATA_OUT                     (GTX9_RXDATA_OUT),
        .RXUSRCLK2_IN                   (GTX9_RXUSRCLK2_IN),
        //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
        .RXEQMIX_IN                     (GTX9_RXEQMIX_IN),
        .RXN_IN                         (GTX9_RXN_IN),
        .RXP_IN                         (GTX9_RXP_IN),
        //---------------------- Receive Ports - RX PLL Ports ----------------------
        .GTXRXRESET_IN                  (GTX9_GTXRXRESET_IN),
        .MGTREFCLKRX_IN                 ({tied_to_ground_i , GTX9_MGTREFCLKRX_IN}),
        .PLLRXRESET_IN                  (GTX9_PLLRXRESET_IN),
        .RXPLLLKDET_OUT                 (GTX9_RXPLLLKDET_OUT),
        .RXRESETDONE_OUT                (GTX9_RXRESETDONE_OUT),
        //---------------- Transmit Ports - TX Data Path interface -----------------
        .TXDATA_IN                      (GTX9_TXDATA_IN),
        .TXOUTCLK_OUT                   (GTX9_TXOUTCLK_OUT),
        .TXUSRCLK2_IN                   (GTX9_TXUSRCLK2_IN),
        //-------------- Transmit Ports - TX Driver and OOB signaling --------------
        .TXDIFFCTRL_IN                  (GTX9_TXDIFFCTRL_IN),
        .TXN_OUT                        (GTX9_TXN_OUT),
        .TXP_OUT                        (GTX9_TXP_OUT),
        .TXPOSTEMPHASIS_IN              (GTX9_TXPOSTEMPHASIS_IN),
        //------------- Transmit Ports - TX Driver and OOB signalling --------------
        .TXPREEMPHASIS_IN               (GTX9_TXPREEMPHASIS_IN),
        //--------------------- Transmit Ports - TX PLL Ports ----------------------
        .GTXTXRESET_IN                  (GTX9_GTXTXRESET_IN),
        .MGTREFCLKTX_IN                 ({tied_to_ground_i , GTX9_MGTREFCLKTX_IN}),
        .PLLTXRESET_IN                  (GTX9_PLLTXRESET_IN),
        .TXPLLLKDET_OUT                 (GTX9_TXPLLLKDET_OUT),
        .TXRESETDONE_OUT                (GTX9_TXRESETDONE_OUT),
        //------------------- Transmit Ports - TX PRBS Generator -------------------
        .TXENPRBSTST_IN                 (GTX9_TXENPRBSTST_IN),
        .TXPRBSFORCEERR_IN              (GTX9_TXPRBSFORCEERR_IN)

    );



    //_________________________________________________________________________
    //_________________________________________________________________________
    //GTX10  (X0Y10)

    Gem_firefly_gtx #
    (
        // Simulation attributes
        .GTX_SIM_GTXRESET_SPEEDUP   (WRAPPER_SIM_GTXRESET_SPEEDUP),
        
        // Share RX PLL parameter
        .GTX_TX_CLK_SOURCE           ("TXPLL"),
        // Save power parameter
        .GTX_POWER_SAVE              (10'b0000110000)
    )
    gtx10_Gem_firefly_i
    (
        //---------------------- Loopback and Powerdown Ports ----------------------
        .LOOPBACK_IN                    (GTX10_LOOPBACK_IN),
        //------------- Receive Ports - Comma Detection and Alignment --------------
        .RXCOMMADET_OUT                 (GTX10_RXCOMMADET_OUT),
        .RXSLIDE_IN                     (GTX10_RXSLIDE_IN),
        //--------------------- Receive Ports - PRBS Detection ---------------------
        .PRBSCNTRESET_IN                (GTX10_PRBSCNTRESET_IN),
        .RXENPRBSTST_IN                 (GTX10_RXENPRBSTST_IN),
        .RXPRBSERR_OUT                  (GTX10_RXPRBSERR_OUT),
        //----------------- Receive Ports - RX Data Path interface -----------------
        .RXDATA_OUT                     (GTX10_RXDATA_OUT),
        .RXUSRCLK2_IN                   (GTX10_RXUSRCLK2_IN),
        //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
        .RXEQMIX_IN                     (GTX10_RXEQMIX_IN),
        .RXN_IN                         (GTX10_RXN_IN),
        .RXP_IN                         (GTX10_RXP_IN),
        //---------------------- Receive Ports - RX PLL Ports ----------------------
        .GTXRXRESET_IN                  (GTX10_GTXRXRESET_IN),
        .MGTREFCLKRX_IN                 ({tied_to_ground_i , GTX10_MGTREFCLKRX_IN}),
        .PLLRXRESET_IN                  (GTX10_PLLRXRESET_IN),
        .RXPLLLKDET_OUT                 (GTX10_RXPLLLKDET_OUT),
        .RXRESETDONE_OUT                (GTX10_RXRESETDONE_OUT),
        //---------------- Transmit Ports - TX Data Path interface -----------------
        .TXDATA_IN                      (GTX10_TXDATA_IN),
        .TXOUTCLK_OUT                   (GTX10_TXOUTCLK_OUT),
        .TXUSRCLK2_IN                   (GTX10_TXUSRCLK2_IN),
        //-------------- Transmit Ports - TX Driver and OOB signaling --------------
        .TXDIFFCTRL_IN                  (GTX10_TXDIFFCTRL_IN),
        .TXN_OUT                        (GTX10_TXN_OUT),
        .TXP_OUT                        (GTX10_TXP_OUT),
        .TXPOSTEMPHASIS_IN              (GTX10_TXPOSTEMPHASIS_IN),
        //------------- Transmit Ports - TX Driver and OOB signalling --------------
        .TXPREEMPHASIS_IN               (GTX10_TXPREEMPHASIS_IN),
        //--------------------- Transmit Ports - TX PLL Ports ----------------------
        .GTXTXRESET_IN                  (GTX10_GTXTXRESET_IN),
        .MGTREFCLKTX_IN                 ({tied_to_ground_i , GTX10_MGTREFCLKTX_IN}),
        .PLLTXRESET_IN                  (GTX10_PLLTXRESET_IN),
        .TXPLLLKDET_OUT                 (GTX10_TXPLLLKDET_OUT),
        .TXRESETDONE_OUT                (GTX10_TXRESETDONE_OUT),
        //------------------- Transmit Ports - TX PRBS Generator -------------------
        .TXENPRBSTST_IN                 (GTX10_TXENPRBSTST_IN),
        .TXPRBSFORCEERR_IN              (GTX10_TXPRBSFORCEERR_IN)

    );



    //_________________________________________________________________________
    //_________________________________________________________________________
    //GTX11  (X0Y11)

    Gem_firefly_gtx #
    (
        // Simulation attributes
        .GTX_SIM_GTXRESET_SPEEDUP   (WRAPPER_SIM_GTXRESET_SPEEDUP),
        
        // Share RX PLL parameter
        .GTX_TX_CLK_SOURCE           ("TXPLL"),
        // Save power parameter
        .GTX_POWER_SAVE              (10'b0000110000)
    )
    gtx11_Gem_firefly_i
    (
        //---------------------- Loopback and Powerdown Ports ----------------------
        .LOOPBACK_IN                    (GTX11_LOOPBACK_IN),
        //------------- Receive Ports - Comma Detection and Alignment --------------
        .RXCOMMADET_OUT                 (GTX11_RXCOMMADET_OUT),
        .RXSLIDE_IN                     (GTX11_RXSLIDE_IN),
        //--------------------- Receive Ports - PRBS Detection ---------------------
        .PRBSCNTRESET_IN                (GTX11_PRBSCNTRESET_IN),
        .RXENPRBSTST_IN                 (GTX11_RXENPRBSTST_IN),
        .RXPRBSERR_OUT                  (GTX11_RXPRBSERR_OUT),
        //----------------- Receive Ports - RX Data Path interface -----------------
        .RXDATA_OUT                     (GTX11_RXDATA_OUT),
        .RXUSRCLK2_IN                   (GTX11_RXUSRCLK2_IN),
        //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
        .RXEQMIX_IN                     (GTX11_RXEQMIX_IN),
        .RXN_IN                         (GTX11_RXN_IN),
        .RXP_IN                         (GTX11_RXP_IN),
        //---------------------- Receive Ports - RX PLL Ports ----------------------
        .GTXRXRESET_IN                  (GTX11_GTXRXRESET_IN),
        .MGTREFCLKRX_IN                 ({tied_to_ground_i , GTX11_MGTREFCLKRX_IN}),
        .PLLRXRESET_IN                  (GTX11_PLLRXRESET_IN),
        .RXPLLLKDET_OUT                 (GTX11_RXPLLLKDET_OUT),
        .RXRESETDONE_OUT                (GTX11_RXRESETDONE_OUT),
        //---------------- Transmit Ports - TX Data Path interface -----------------
        .TXDATA_IN                      (GTX11_TXDATA_IN),
        .TXOUTCLK_OUT                   (GTX11_TXOUTCLK_OUT),
        .TXUSRCLK2_IN                   (GTX11_TXUSRCLK2_IN),
        //-------------- Transmit Ports - TX Driver and OOB signaling --------------
        .TXDIFFCTRL_IN                  (GTX11_TXDIFFCTRL_IN),
        .TXN_OUT                        (GTX11_TXN_OUT),
        .TXP_OUT                        (GTX11_TXP_OUT),
        .TXPOSTEMPHASIS_IN              (GTX11_TXPOSTEMPHASIS_IN),
        //------------- Transmit Ports - TX Driver and OOB signalling --------------
        .TXPREEMPHASIS_IN               (GTX11_TXPREEMPHASIS_IN),
        //--------------------- Transmit Ports - TX PLL Ports ----------------------
        .GTXTXRESET_IN                  (GTX11_GTXTXRESET_IN),
        .MGTREFCLKTX_IN                 ({tied_to_ground_i , GTX11_MGTREFCLKTX_IN}),
        .PLLTXRESET_IN                  (GTX11_PLLTXRESET_IN),
        .TXPLLLKDET_OUT                 (GTX11_TXPLLLKDET_OUT),
        .TXRESETDONE_OUT                (GTX11_TXRESETDONE_OUT),
        //------------------- Transmit Ports - TX PRBS Generator -------------------
        .TXENPRBSTST_IN                 (GTX11_TXENPRBSTST_IN),
        .TXPRBSFORCEERR_IN              (GTX11_TXPRBSFORCEERR_IN)

    );



endmodule

    
